"""
parser.py

Parses JSON generated by the analysis model.
"""

import json

from dataclasses import dataclass

from constants import (
    ACTION_UNKNOWN,
    INTENT_UNKNOWN,
    PRIORITY_NORMAL,
    SENTIMENT_NEUTRAL
)


# =====================================================
# Parsed Response
# =====================================================

@dataclass
class ParsedResponse:

    action: str = ACTION_UNKNOWN

    intent: str = INTENT_UNKNOWN

    sentiment: str = SENTIMENT_NEUTRAL

    priority: str = PRIORITY_NORMAL

    confidence: float = 0.0

    reason: str = ""


# =====================================================
# Parser
# =====================================================

def parse_response(llm_output: str):
    """
    Parse the JSON returned by Qwen.

    Parameters
    ----------
    llm_output : str

    Returns
    -------
    ParsedResponse
    """

    try:

        data = json.loads(llm_output)

    except json.JSONDecodeError:

        return ParsedResponse()

    return ParsedResponse(

        action=data.get(
            "action",
            ACTION_UNKNOWN
        ),

        intent=data.get(
            "intent",
            INTENT_UNKNOWN
        ),

        sentiment=data.get(
            "sentiment",
            SENTIMENT_NEUTRAL
        ),

        priority=data.get(
            "priority",
            PRIORITY_NORMAL
        ),

        confidence=float(

            data.get(
                "confidence",
                0.0
            )

        ),

        reason=data.get(
            "reason",
            ""
        )

    )


# =====================================================
# Debug
# =====================================================

def print_parsed(parsed: ParsedResponse):
    """
    Print parsed information.
    """

    print()

    print("=" * 60)

    print("Parsed Response")

    print("=" * 60)

    print("Action      :", parsed.action)

    print("Intent      :", parsed.intent)

    print("Sentiment   :", parsed.sentiment)

    print("Priority    :", parsed.priority)

    print("Confidence  :", parsed.confidence)

    print("Reason      :", parsed.reason)

    print("=" * 60)